[package]
name = "yapa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.5"
either = "1.15.0"
pest = "2.8"
pest_derive = "2.8"
